# name =input("Input Your Name: ")
# nim =input("Input Your Nim: ")

# print(".............................................")
# print("Welcome to" ,name                             )
# print("With Your Nim" ,nim                           )
# print(".............................................")


# print("Question No.1")
# print("Dik sisi = 6, Sebutkan nama dan hitunglah luas bangun datar tersebut!")
# bd1 = input("Nama Bangun Datar = ")
# sisi = eval(input("sisi : "))
# sisi2 = eval(input("sisi2 : "))
# print("Bangun datar tersebut adalah",bd1,"dan luas bangun datar tersebut adalah",sisi*sisi2)
# print()
# print()

# print("Question No.2")
# print("Dik alas = 7, tinggi = 8, hitunglah luas bangun datar tersebut!")
# bd2 = input("Nama Bangun Datar = ")
# alas = eval(input("alas : "))
# tinggi = eval(input("tinggi : "))
# print("Bangun datar tersebut adalah",bd2,"dan luas bangun datar tersebut adalah",alas*tinggi/2)
# print()
# print()

# print("Question No.3")
# print("Dik panjang = 4, Lebar = 9, sebutkan nama dan hitunglah luas bangun datar tersebut")
# bd3 = input("Nama Bangun Datar : ")
# panjang = eval(input("panjang : "))
# lebar = eval(input("lebar : "))
# print("Bangun datar tersebut adalah",bd3,"dan luas bangun datar tersebut adalah",panjang*lebar)
# print()
# print()

# print("Question No.4")
# print("Dik jari-jari = 56, sebutkan nama dan hitunglah luas bangun datar tersebut")
# bd4 = input("Nama Bangun Datar : ")
# phi = float(input("π : "))
# jariJari = float(input("r : "))
# print("Bangun datar tersebut adalah",bd4,"dan luas bangun datar tersebut adalah",phi*jariJari*jariJari)
# print()
# print()

# print("Question No.5")
# print("Diagonal I = 4, diagonal II = 8, sebutkan nama dan hitunglah luas bangun datar tersebut")
# bd5 = input("Nama Bangun Datar : ")
# d1 = float(input("d1 : "))
# d2 = float(input("d2 : "))
# print("Bangun datar tersebut adalah",bd5,"dan luas bangun datar tersebut adalah",d1*d2/2)
# print()
# print()

# print ("Question No.6")
# print("Diketahui Sisi AB dan CD sejajar, sisi Ab = 6, sisi CD = 8, tinggi = 3. Sebutkan Nama dan hitunglah Luas Bangun datar tersebut!")
# bd6 = input("Nama Bangun datar tersebut : ")
# g = eval(input("Sisi AB : "))
# h = eval(input("Sisi CD : "))
# i = eval(input("Tinggi : "))
# print ("Bangun datar tersebut adalah",bd6,"dan luas bangun datar tersebut adalah ",(g+h)*i/2)
# print()
# print()

print ("Question No.7")
print ("Diketahui Jajargenjang dengan alas = 9, Tinggi = 7, nhitunglah Luas Bangun datar tersebut!")
bd7 = input("Nama Bangun datar tersebut : ")
j = eval(input("Alas : "))
k = eval(input("Tinggi : "))
print ("Bangun datar tersebut adalah",bd7,"luas bangun datar jajargenjang  adalah ",j*k)
print()
print()
